[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = []

# This file tells Render to use pip instead of Poetry
# Since we don't have Poetry dependencies, Render will fall back to pip
